version: "3"

services:
  app:
    build: .
    container_name: employees-app
    ports:
      - 3002:3000
    environment:
      - environment=production
      - REDIS_HOST=redis
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DATABASE=employees
    command: npm start
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: employees-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
  redis:
    image: redis
    container_name: employees-redis
    ports:
      - 6379:6379
    command: redis-server